version: '3.6'
services:
    nginx:
      container_name: nginx
      image: nginx:latest
      ports:
        - target: 80
          published: 80
          protocol: tcp
      volumes:
        - type: bind
          source: ./nginx/nginx.conf
          target: /etc/nginx/nginx.conf
      depends_on:
        - Service1
        - crystals
        - cards
        - readings
    Service1:
       image: service1
       build:
         context: ./Service1
       ports:
         - target: 5000
           published: 5000
           protocol: tcp
           
    crystals:
       image: crystals
       build: 
         context: ./crystals
         dockerfile: Dockerfile
    cards:
       image: cards
       build: 
         context: ./cards
         dockerfile: Dockerfile
    readings:
       image: readings
       build: 
         context: ./readings
         dockerfile: Dockerfile

