version: '3.6'
services:
    nginx:
      container_name: nginx
      image: nginx:latest
      ports:
        - target: 80
          published: 80
          protocol: tcp
      volumes:
        - type: bind
          source: ./nginx/nginx.conf
          target: /etc/nginx/nginx.conf
      depends_on:
        - service1
        - crystals
        - cards
        - readings
    service1:
       image: jenkins:5000/service1:build-${BUILD_NUMBER}
       build:
         context: ./service1
       ports:
       - target: 5000
         published: 5000
         protocol: tcp
           
    crystals:
       image: jenkins:5000/crystal:build-${BUILD_NUMBER}
       build: 
         context: ./crystals
         dockerfile: Dockerfile
       ports:
       - target: 5001
         published: 5001
         protocol: tcp

    cards:
       image: jenkins:5000/cards:build-${BUILD_NUMBER}
       build: 
         context: ./cards
         dockerfile: Dockerfile
       ports:
       - target: 5002
         published: 5002
         protocol: tcp

    readings:
       image: jenkins:5000/readings:build-${BUILD_NUMBER}
       build: 
         context: ./readings
         dockerfile: Dockerfile
       ports:
       - target: 5003
         published: 5003
         protocol: tcp

